/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcup;
/**
 *
 * @author rishigoel
 */
public class Shootout extends javax.swing.JFrame {
//variable declaration
    int y=0;
        String [] playerlist=new String[5];
        int xi;
        int score=0;
        int shot=0;
        String[] history=new String [5];
    /**
     * Creates new form Shootout
     */
    public Shootout() {
        //sets everything invisible and plays the music method
        initComponents();
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jButton2.setVisible(false);
        jLabel11.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jButton8.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jButton9.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel23.setVisible(false);
        jLabel10.setVisible(false);
Players x=new Players();
        x.music();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/World-Cup-2014-Brasil-logo-03.jpg")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1024, 598));

        jLabel21.setText("jLabel21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(null);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 75, 29);

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(10, 120, 120, 23);

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(10, 150, 120, 23);

        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(10, 180, 120, 23);

        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("jRadioButton4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(10, 210, 120, 23);

        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("jRadioButton5");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(10, 240, 120, 23);

        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("jRadioButton6");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(10, 270, 120, 20);

        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("jRadioButton7");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(10, 300, 120, 23);

        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("jRadioButton8");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(10, 330, 120, 23);

        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("jRadioButton9");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(10, 360, 120, 23);

        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("jRadioButton10");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(10, 390, 128, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Your 5 Players");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 150, 50);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Shooting order is the same as selection order");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 180, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Shooters");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(900, 70, 60, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(900, 100, 110, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(900, 130, 110, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(900, 160, 110, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(900, 190, 110, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(900, 220, 110, 16);

        jButton2.setText("Begin!!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(880, 250, 86, 29);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Click where you Want to Shoot");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 30, 510, 30);

        jButton3.setText("Shoot!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 120, 97, 29);

        jButton4.setText("Shoot!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 390, 84, 29);

        jButton5.setText("Shoot!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 110, 84, 29);

        jButton6.setText("Shoot!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(710, 390, 84, 29);

        jLabel12.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(780, 10, 96, 50);

        jButton7.setText("Shoot!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(460, 120, 84, 29);

        jLabel13.setFont(new java.awt.Font("News Gothic MT", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 10, 690, 16);

        jButton8.setText("Play Again");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(440, 260, 97, 29);

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/balon-adidas-brazuca-mini-blanco-0.png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 460, 100, 110);

        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/hart.png")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(310, 120, 450, 390);

        jButton9.setText("Next Shot");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(570, 30, 97, 29);

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/hart3.png")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 40, 540, 370);

        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/hart2.png")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(100, 250, 550, 340);

        jLabel18.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/hart4.png")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(410, 30, 480, 390);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(270, 280, 550, 0);

        jLabel23.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/hart5.png")); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(430, 250, 601, 303);

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/World-Cup-2014-Brasil-logo-03.jpg")); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 1024, 578);

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/rishigoel/NetBeansProjects/WorldCup/net.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 1130, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//makes everything visible so the game can start 
        jButton1.setVisible(false);
        jLabel10.setVisible(false);
        jLabel20.setVisible(true);
jLabel1.setVisible(true);
jRadioButton1.setVisible(true);
jRadioButton2.setVisible(true);
jRadioButton3.setVisible(true);
jRadioButton4.setVisible(true);
jRadioButton5.setVisible(true);
jRadioButton6.setVisible(true);
jRadioButton7.setVisible(true);
jRadioButton8.setVisible(true);
jRadioButton9.setVisible(true);
jRadioButton10.setVisible(true);
jLabel3.setVisible(true);
String [] list=new String [10];
Players x=new Players();
list=x.players1();
jRadioButton1.setText(list[0]);
jRadioButton2.setText(list[1]);
jRadioButton3.setText(list[2]);
jRadioButton4.setText(list[3]);
jRadioButton5.setText(list[4]);
jRadioButton6.setText(list[5]);
jRadioButton7.setText(list[6]);
jRadioButton8.setText(list[7]);
jRadioButton9.setText(list[8]);
jRadioButton10.setText(list[9]);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button
        playerlist[y]=jRadioButton1.getText();
        y++;
        jRadioButton1.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button
        playerlist[y]=jRadioButton2.getText();
        y++;  
        jRadioButton2.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button

        playerlist[y]=jRadioButton3.getText();
        y++;   
        jRadioButton3.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed

                //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button
playerlist[y]=jRadioButton4.getText();
        y++;   
        jRadioButton4.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button

        playerlist[y]=jRadioButton5.getText();
        y++;   
        jRadioButton5.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button

        playerlist[y]=jRadioButton6.getText();
        y++;   
        jRadioButton6.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false); 
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        jLabel10.setVisible(false);
        y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button

        playerlist[y]=jRadioButton7.getText();
        y++;   
        jRadioButton7.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button

        playerlist[y]=jRadioButton8.getText();
        y++;   
        jRadioButton8.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button

        playerlist[y]=jRadioButton9.getText();
        y++;   
        jRadioButton9.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        //stores the shooter selection an an array and tracks the number of players selected. This is the same for each radio button

        playerlist[y]=jRadioButton10.getText();
        y++;   
        jRadioButton10.setVisible(false);
        if (y==5) {
          jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);  
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        jLabel5.setText(playerlist[0]);
        jLabel5.setVisible(true);
        jLabel6.setText(playerlist[1]);
        jLabel6.setVisible(true);
        jLabel7.setText(playerlist[2]);
        jLabel7.setVisible(true);
        jLabel8.setText(playerlist[3]);
        jLabel8.setVisible(true);
        jLabel9.setText(playerlist[4]);
        jLabel9.setVisible(true);
        jButton2.setVisible(true);
        y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //allows the player to start shooting
        jButton2.setVisible(false);
        jLabel20.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel11.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jLabel12.setText("Score");
        jLabel12.setVisible(true);
        jLabel13.setText("Shot History:");
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jLabel10.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//the player chooses where they shoot.  Tracks the shot total and the score.  Prints out a statement on whether or not the player scored.  MOves the goalie and ball images depending where the shot/save is
jLabel14.setLocation(100,100);
jLabel15.setVisible(false);
xi=1;
Players yi=new Players();
if (shot!=5) {
int save=yi.save();
if (save ==1) {
    jLabel16.setVisible(true);
}
if (save ==2) {
    jLabel17.setVisible(true);
}
if (save ==3) {
    jLabel18.setVisible(true);
}
if (save ==4) {
    jLabel23.setVisible(true);
}
if (save ==5) {
    jLabel15.setVisible(true);
}
if (save==xi) {
    jLabel11.setText(playerlist[y] +" has missed! What a save by the keeper!");
    shot++;
    history[y]="Miss, ";
    y++;
}
if(save!=xi) {
       jLabel11.setText("What a goal by "+playerlist[y]); 
       history[y]="Goal, ";
       y++;
       score++;
       shot++;
       jLabel12.setText("Score: "+score);
    }
jButton9.setVisible(true);
jButton3.setVisible(false);
jButton4.setVisible(false);
jButton5.setVisible(false);
jButton6.setVisible(false);
jButton7.setVisible(false);
}
if (shot==5) {
    jButton3.setVisible(false);
    jButton4.setVisible(false);
    jButton5.setVisible(false);
    jButton6.setVisible(false);
    jButton7.setVisible(false);
    jLabel13.setText("Shot History: "+history[0]+history[1]+history[2]+history[3]+history[4]);
    jButton8.setVisible(true);
    jButton9.setVisible(false);
    if (score==5) {
    jLabel11.setText("You have scored "+score+" goals out of five shots. You win!");
    }
    if (score!=5) {
       jLabel11.setText("You have scored "+score+" goals out of five shots. Better luck next time"); 
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//the player chooses where they shoot.  Tracks the shot total and the score.  Prints out a statement on whether or not the player scored.  MOves the goalie and ball images depending where the shot/save is
jLabel15.setVisible(false);
        xi=2;
jLabel14.setLocation(100,400);
Players yi=new Players();
if (shot!=5) {
int save=yi.save();
if (save ==1) {
    jLabel16.setVisible(true);
}
if (save ==2) {
    jLabel17.setVisible(true);
}
if (save ==3) {
    jLabel18.setVisible(true);
}
if (save ==4) {
    jLabel23.setVisible(true);
}
if (save ==5) {
    jLabel15.setVisible(true);
}
if (save==xi) {
    jLabel11.setText(playerlist[y] +" has missed! What a save by the keeper!");
    shot++;
    history[y]="Miss, ";
    y++;
}
if(save!=xi) {
       jLabel11.setText("What a goal by "+playerlist[y]); 
       history[y]="Goal, ";
       y++;
       score++;
       shot++;
      jLabel12.setText("Score: "+score);
    }
jButton9.setVisible(true);
jButton3.setVisible(false);
jButton4.setVisible(false);
jButton5.setVisible(false);
jButton6.setVisible(false);
jButton7.setVisible(false);
}
if (shot==5) {
    jButton3.setVisible(false);
    jButton4.setVisible(false);
    jButton5.setVisible(false);
    jButton6.setVisible(false);
    jButton7.setVisible(false);
    jLabel13.setText("Shot History: "+history[0]+history[1]+history[2]+history[3]+history[4]);
    jButton8.setVisible(true);
    jButton9.setVisible(false);
    if (score==5) {
    jLabel11.setText("You have scored "+score+" goals out of five shots. You win!");
    }
    if (score!=5) {
       jLabel11.setText("You have scored "+score+" goals out of five shots. Better luck next time"); 
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//the player chooses where they shoot.  Tracks the shot total and the score.  Prints out a statement on whether or not the player scored.  MOves the goalie and ball images depending where the shot/save is
jLabel15.setVisible(false);
        xi=3;
jLabel14.setLocation(700,100);
Players yi=new Players();
if (shot!=5) {
int save=yi.save();
if (save ==1) {
    jLabel16.setVisible(true);
}
if (save ==2) {
    jLabel17.setVisible(true);
}
if (save ==3) {
    jLabel18.setVisible(true);
}
if (save ==4) {
    jLabel23.setVisible(true);
}
if (save ==5) {
    jLabel15.setVisible(true);
}
if (save==xi) {
    jLabel11.setText(playerlist[y] +" has missed! What a save by the keeper!");
    history[y]="Miss, ";
    shot++;
    y++;
}
if(save!=xi)  {
       jLabel11.setText("What a goal by "+playerlist[y]); 
       history[y]="Goal, ";
       y++;
       score++;
       shot++;
       jLabel12.setText("Score: "+score);
    }
jButton9.setVisible(true);
jButton3.setVisible(false);
jButton4.setVisible(false);
jButton5.setVisible(false);
jButton6.setVisible(false);
jButton7.setVisible(false);
}
if (shot==5) {
    jButton3.setVisible(false);
    jButton4.setVisible(false);
    jButton5.setVisible(false);
    jButton6.setVisible(false);
    jButton7.setVisible(false);
    jLabel13.setText("Shot History: "+history[0]+history[1]+history[2]+history[3]+history[4]);
    jButton8.setVisible(true);
    jButton9.setVisible(false);
    if (score==5) {
    jLabel11.setText("You have scored "+score+" goals out of five shots. You win!");
    }
    if (score!=5) {
       jLabel11.setText("You have scored "+score+" goals out of five shots. Better luck next time"); 
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//the player chooses where they shoot.  Tracks the shot total and the score.  Prints out a statement on whether or not the player scored.  MOves the goalie and ball images depending where the shot/save is
jLabel15.setVisible(false);
        xi=4;
jLabel14.setLocation(700,400);
Players yi=new Players();
if (shot!=5) {
int save=yi.save();
if (save ==1) {
    jLabel16.setVisible(true);
}
if (save ==2) {
    jLabel17.setVisible(true);
}
if (save ==3) {
    jLabel18.setVisible(true);
}
if (save ==4) {
    jLabel23.setVisible(true);
}
if (save ==5) {
    jLabel15.setVisible(true);
}
if (save==xi) {
    jLabel11.setText(playerlist[y] +" has missed! What a save by the keeper!");
    history[y]="Miss, ";
    shot++;
    y++;
}
if(save!=xi)  {
       jLabel11.setText("What a goal by "+playerlist[y]); 
       history[y]="Goal, ";
       y++;
       score++;
       shot++;
       jLabel12.setText("Score: "+score);
    }
jButton9.setVisible(true);
jButton3.setVisible(false);
jButton4.setVisible(false);
jButton5.setVisible(false);
jButton6.setVisible(false);
jButton7.setVisible(false);
}
if (shot==5) {
    jButton3.setVisible(false);
    jButton4.setVisible(false);
    jButton5.setVisible(false);
    jButton6.setVisible(false);
    jButton7.setVisible(false);
    jLabel13.setText("Shot History: "+history[0]+history[1]+history[2]+history[3]+history[4]);
    jButton8.setVisible(true);
    jButton9.setVisible(false);
    if (score==5) {
    jLabel11.setText("You have scored "+score+" goals out of five shots. You win!");
    }
    if (score!=5) {
       jLabel11.setText("You have scored "+score+" goals out of five shots. Better luck next time"); 
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//the player chooses where they shoot.  Tracks the shot total and the score.  Prints out a statement on whether or not the player scored.  MOves the goalie and ball images depending where the shot/save is
jLabel15.setVisible(false);
        xi=5;
jLabel14.setLocation(450,100);
Players yi=new Players();
if (shot!=5) {
int save=yi.save();
if (save ==1) {
    jLabel16.setVisible(true);
}
if (save ==2) {
    jLabel17.setVisible(true);
}
if (save ==3) {
    jLabel18.setVisible(true);
}
if (save ==4) {
    jLabel23.setVisible(true);
}
if (save ==5) {
    jLabel15.setVisible(true);
}
if (save==xi) {
    jLabel11.setText(playerlist[y] +" has missed! What a save by the keeper!");
    history[y]="Miss, ";
    shot++;
    y++;
}
if(save!=xi)  {
       jLabel11.setText("What a goal by "+playerlist[y]); 
       history[y]="Goal, ";
       y++;
       score++;
       shot++;
       jLabel12.setText("Score: "+score);
    }
jButton9.setVisible(true);
jButton3.setVisible(false);
jButton4.setVisible(false);
jButton5.setVisible(false);
jButton6.setVisible(false);
jButton7.setVisible(false);
}
if (shot==5) {
    jButton3.setVisible(false);
    jButton4.setVisible(false);
    jButton5.setVisible(false);
    jButton6.setVisible(false);
    jButton7.setVisible(false);
    jLabel13.setText("Shot History: "+history[0]+history[1]+history[2]+history[3]+history[4]);
    jButton8.setVisible(true);
    jButton9.setVisible(false);
    if (score==5) {
    jLabel11.setText("You have scored "+score+" goals out of five shots. You win!");
    }
    if (score!=5) {
       jLabel11.setText("You have scored "+score+" goals out of five shots. Better luck next time"); 
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //lets the user play again
        jButton1.setVisible(true);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jButton2.setVisible(false);
        
        jLabel11.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jButton8.setVisible(false);
        jLabel2.setVisible(true);
        y=0;
        shot=0;
        score=0;
        jLabel11.setText("Click Where to Shoot");
        jLabel14.setLocation(350,480);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel23.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       //lets the user take the next shot
        jButton9.setVisible(false);
       jLabel14.setLocation(375,480);
       jLabel15.setVisible(true);
jButton3.setVisible(true);
jButton4.setVisible(true);
jButton5.setVisible(true);
jButton6.setVisible(true);
jButton7.setVisible(true);
jLabel16.setVisible(false);
jLabel17.setVisible(false);
jLabel18.setVisible(false);
jLabel23.setVisible(false);
jLabel11.setText("Click where to shoot");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shootout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shootout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shootout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shootout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shootout().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
